### ISSUE TITLE
Add it mplug script directory

### ISSUE THREAD

**Issue by z8512** [CrendKing/mpv-twitch-chat#10]
Mplug is like a package manager but for mpv scripts.
Please add your script there (if already not there) and also installation instructions in manifest - https://github.com/Nudin/mpv-script-directory/blob/master/HOWTO_ADD_INSTALL_INSTRUCTIONS.md

**Comment by CrendKing** [comment]
Thanks for letting me know. However, as I mentioned in #9, to avoid violating Twitch TOS, I'm not embedding the client ID for chat replay. Users of this script needs to fill it in themselves. As I understand, the mplug is mainly aim to automate the installation process, which can't be done for this script due to the client ID. So the only benefit I can see is maybe publicity, which I've already done by adding to https://github.com/mpv-player/mpv/wiki/User-Scripts.

**Comment by z8512** [comment]
Hello and thank you. 
Add instructions in your readme how to install it using mplug. In post-installation instruction state to fill Client ID themselves after installing it using mplug

**Comment by CrendKing** [comment]
Like I said, I don't see the benefit. If user still has to create that option file, research the client ID and fill it in, the actual installation part of the script itself is rather easy in comparison.
