### ISSUE TITLE
New into MPV

### ISSUE THREAD

**Issue by hellishvictor** [CrendKing/mpv-twitch-chat#12]
Hi, I'm new into MPV and more to lua script, so I need some help. I've downloaded a twitch vod, and also its chat on a txt file. Both have the same name, with their respective extensions (VOD.mp4 and VOD.txt). I'm on Win 7 x64 btw. I've created the folders "scripts" and "script-opts" inside MPV, then I've renamed the script from "main.lua" to "Twitch-chat.lua", and put it on the "script" folder. Seems that I need to put a config file on the "script-opts" file, but a example will be appreciated.
Cheers.

**Comment by CrendKing** [comment]
If your question is how to use this script to show chat replay for downloaded files, the answer is no, this script is not design for that purpose. It is for online only.

If your question is how to use this script for its intended environment, all you need to do is install the script (as how you install any mpv plugin) and turn on subtitle when you watch a Twitch VOD URL. The only gimmick is that you need to provide valid Twitch API client ID, which you need to find out yourself.

**Comment by hellishvictor** [comment]
> If your question is how to use this script to show chat replay for downloaded files, the answer is no, this script is not design for that purpose. It is for online only.
> 
Too bad.
> you need to provide valid Twitch API client ID, which you need to find out yourself.
>
Ok, you killed me with that. I'm on the wrong place. Ty anyway.

**Comment by CrendKing** [comment]
> Too bad.

Because I believe nobody downloads the whole VOD to disk and then watch. It's not practical.

> Ok, you killed me with that. I'm on the wrong place. Ty anyway.

For legal reason. Twitch does not allow anybody else except themselves to show chat replay. Which brings me to this question:

> I've downloaded a twitch vod, and also its chat on a txt file.

How do you download the chat into a txt file in the first place? If you did it by scraping the page, I suggest you stay with www.twitch.tv. Otherwise, you should already have known the client ID to use.
